# Generated by Django 5.1.6 on 2025-03-14 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Food', 'Food'), ('Transport', 'Transport'), ('School', 'School'), ('Entertainment', 'Entertainment'), ('Health', 'Health'), ('Other', 'Other')], max_length=50),
        ),
    ]
