# Generated by Django 5.1.6 on 2025-03-14 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='date',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
    ]
