# Generated by Django 5.1.6 on 2025-03-14 22:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_budget_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
